// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apntrvxbjcrkubfsicqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwbnRydnhiamNya3ViZnNpY3FjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NDk4MjEsImV4cCI6MjA2NTMyNTgyMX0.E94mIpvAkxc33dmAGCQnKskkI31J20WXyy_SsbibcI4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);